### ISSUE TITLE
[ENHANCE] Pending Verication Stamps Also Showing up in Get Check Section

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#40] opened 2024-02-11 18:50 UTC
Currently redundant, should no longer show up once in pending section
<img width="776" alt="" src="https://github.com/PotLock/nadabot-app/assets/45281667/cfba0b26-58e1-403c-9940-0d8ab2b4f175">

**Comment by wpdas** [comment] 2024-02-14 22:29
@codingshot I ain't able to reproduce this issue. Can you check this again, please?

**Comment by wpdas** [comment] 2024-02-15 14:16
Closing because we can't reproduce this issue.

**Closed by wpdas** 2024-02-15 14:16 UTC
Labels: enhancement
